[book]
authors = ["asforest"]
language = "zh"
multilingual = false
src = "pages"
title = "mcpatch docs"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/BalloonUpdate/McPatchDocs"
git-repository-icon = "fa-github"
edit-url-template="https://github.com/BalloonUpdate/McPatchDocs/edit/master/{path}"
additional-css = ["theme/highlight.css", "theme/line-height.css"]
additional-js  = []
