name: Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }} # -${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      
      - name: set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.68.0
          override: true
          
      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
      
      - name: mdbook
        run: |
          cargo install mdbook@0.4.28
      
      - name: render htmls
        run: |
          mdbook build

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
#         if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
